core/system.h
libretro/libretro.c
libretro/osd.h

Available options for core-provided aspect ratio are "auto", "NTSC PAR" and "PAL PAR".
- NTSC PAR forces pixel aspect ratio of NTSC tvs always, regardless of game or core region
- PAL PAR forces pixel aspect ratio of PAL tvs always, regardless of game or core region
- auto works as following
- NTSC PAR is used when core region is set to auto and game region is NTSC, or core region is set to ntsc-u or ntsc-j.
- PAL PAR is used when core region is set to auto and game region is PAL, or core region is set to pal.
- 6:5 PAR is used for Game Gear games, if core options Borders and Game Gear extended screen are both disabled

Add new core option: Core-provided aspect ratio.

---

Makefile.libretro
libretro/libretro.c

This seems to add support for non-standard Action Replay and Game Genie cheat code formats for Master System (00xx-xxyy, xxxx:yy and shortened ABC-DEF instead of just 00xxxx:yy and ABC-DEF-GHI that were already supported). Not a good idea in my opinion to re-invent standards and adapt emulators every time a new format is invented by someone but I guess it's too late now.
Also adds support for "multiline" cheat format used in retroarch ( basically it's just cheat codes put on the same line for some unknown reason)

[libretro] merge cheat support changes

---

core/sound/ym3438.c
core/sound/ym3438.h

On invalid port YM chip outputs internal bus noise. In general it is previous success status read value, which then discharges. Discharge time is greatly differs between YM2612 and YM3438 due to NMOS/CMOS difference and is a reason why YM3438 is considered not compatible with YM2612.

[Core/Sound] accurate YM2612/3438 status read emulation on invalid port

---

core/sound/ym3438.c
core/sound/ym3438.h
libretro/libretro.c

Apparently YM3438 on Sega TeraDrive behaves and sounds exactly like ASIC one, so there's no more point to have this option anymore.

[Core/Sound] Nuked OPN2: removed discrete ym3438 core

---

core/cpuhook.h
core/debug/cpuhook.c
core/debug/cpuhook.h
core/m68k/m68k.h
core/m68k/m68kcpu.c
core/m68k/m68kcpu.h
core/vdp_ctrl.c
libretro/libretro_msvc/genesis_plus_gx_libretro.vcxproj
libretro/libretro_msvc/genesis_plus_gx_libretro.vcxproj.filters
sdl/Makefile.sdl1
sdl/Makefile.sdl2
sdl/gx_vstudio/gx_vstudio.vcxproj
sdl/gx_vstudio/gx_vstudio.vcxproj.filters

Resolves #85
Can be used by a frontend to implement breakpoints or trace-logging.
Currently hooked:
* M68K executing/reading/writing
* VDP reading/writing (only for MegaDrive)

Add CPU hooking functionality

---

core/sound/sound.c

This fixes:
core/sound/sound.c:47:25: warning: extra tokens at end of #ifdef directive
47 | #ifdef HAVE_YM3438_CORE || HAVE_OPLL_CORE

Fixed extra #ifdef token warning in sound.c

---

core/cd_hw/libchdr/src/chd.c

We need to align because of GCC auto-vectorization using possibly NEON code for zlib and lzma decompression routines.
Issue was encountered on libretro-flycast first on rpi4 (aarch32 userland).
Here is the minimal fix.
@ekeeke => We should discuss on how to update your libchdr implementation as it's really old, lots of improvements and fixes happened meanwhile.

Fix crash loading CHD on some ARM boards (minimal changes)

---

core/vdp_ctrl.c
libretro/libretro.c
libretro/osd.h

As discussed over here https://github.com/libretro/Genesis-Plus-GX/issues/218, This adds an option to hide the left border of Master System games by chopping off 8 pixels of both left and right sides of the screen:
<details>
<summary>Sonic The Hedgehog</summary>
</details>
This is somewhat different from how SMS-Plus-GX does, as I didn't know how to shift the screen without creating a black bar, but all by all it doesn't look bad, and of the games I've tested this out with, none seemed to make much use of the 8 rightmost pixels anyway:
<details>
<summary>Fantasy Zone</summary>
</details>
<details>
<summary>Deep Duck Trouble Starring Donald Duck</summary>
</details>
<details>
<summary>Asterix and the Great Rescue</summary>
</details>
<details>
<summary>OutRun</summary>
</details>
<details> …

Libretro: Add an option to remove left side border ( Sega Master System)

---

Makefile.gc
Makefile.wii
gx/gui/cheats.c
gx/gui/filesel.c
gx/gui/gui.h
gx/gui/legal.c
gx/gui/menu.c
gx/gx_video.c

Use the bin2o generated headers instead of replacing it with a direct command line. This avoids the risk of breakage if updated tooling replaces bin2s as well as ensuring source files which reference the data are recompiled when the data changes.
I've also updated the Makefile with the latest changes that allow verbosity to be controlled with `make V=1` and mitigate for issues on some systems with parallel building.

Use generated headers

---

core/cart_hw/sms_cart.c

This is one of the few games designed for the PAL regions, and as such runs too fast by default.

Add Power Strike II to internal database as 50Hz game

---

libretro/libretro.c

Upstreams https://github.com/libretro/Genesis-Plus-GX/commit/81fce948ac57abfcb7b7d9487f08a0d0650f94f8, fixing https://github.com/libretro/Genesis-Plus-GX/issues/282

[Libretro] Fix the "Hiding Master System Side Borders" option not working with Blargg NTSC filter'

---

core/vdp_ctrl.c
core/vdp_render.c
core/vdp_render.h
gcw0/config.c
gcw0/config.h
gx/config.c
gx/config.h
libretro/libretro.c
libretro/libretro_core_options.h
libretro/osd.h
psp2/config.c
psp2/config.h
sdl/config.c
sdl/config.h

Same as here https://github.com/libretro/Genesis-Plus-GX/pull/306
This emulation hack allows allows each cell to be vscrolled individually, instead of being limited to 2-cell (16px). The offset of the new, intermediary cell is calculated as an average of the offset of the current 2-cell and the offset of the next 2-cell.
Before / after comparisons:

Enchanced per-tile vertical scroll

---

core/cart_hw/eeprom_93c.c
core/cart_hw/eeprom_93c.h
core/cart_hw/eeprom_i2c.c
core/cart_hw/eeprom_i2c.h
core/cart_hw/eeprom_spi.c
core/cart_hw/eeprom_spi.h
core/cart_hw/sram.c
core/cart_hw/sram.h
core/input_hw/mouse.c
core/m68k/s68kcpu.c
core/sound/psg.c
core/sound/ym2612.c
libretro/libretro.c

This will be required for upcoming gcc and clang versions.
Reference: https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240

Fix -Werror=strict-prototypes

---

libretro/libretro.c

Add .bin extension support for archives，solve this issues https://github.com/ekeeke/Genesis-Plus-GX/issues/496#issuecomment-1483882241

(libretro) Add .bin extension support for archives

---

libretro/libretro.c
libretro/libretro_core_options.h

Add an option for the backup ram cart to be configurable per-cart or per-game.
Ported from downstream [#326](https://github.com/libretro/Genesis-Plus-GX/pull/326).

[libretro] Port Backup Ram Cart changes from downstream

---

core/genesis.c

This PR fixes the zstate variable comment error discussed in #508

fix error in zstate comment

---

libretro/libretro_core_options.h

Fixes https://github.com/libretro/Genesis-Plus-GX/issues/341

Fix nonstandard default for CD add-on (MD mode)

---

core/m68k/m68kcpu.c
core/m68k/m68kcpu.h
core/macros.h
core/vdp_ctrl.c

Even when HOOK_CPU is defined, actual hooks are assigned not very frequently, so we can speed things up by hinting the compiler what the most common scenario is. Might be useful in other situations but I don't know the code that well.

Use the UNLIKELY() macro for cpu hooks

---

libretro/libretro.c
libretro/libretro_core_options.h

Adds https://github.com/libretro/Genesis-Plus-GX/commit/ba9fc37cfa4930311a9c77b1d8a23df0cae95e9a to upstream with an addition update to the option description suggested here:
https://github.com/libretro/Genesis-Plus-GX/issues/358

Add Force VDP Mode option

---

core/m68k/m68kcpu.h

[Last time](https://github.com/ekeeke/Genesis-Plus-GX/pull/554) we missed this case, sorry.

add UNLIKELY() macro to address error emulation
